name: Build and test

on: [push, pull_request]

jobs:
  linux:
    name: Build & Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
